version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"  
    ports:
      - "3307:3306"

  app:
    build: .
    stdin_open: true
    tty: true   